### ISSUE TITLE
Left panel design is not up to date

### ISSUE THREAD

**Issue by bmlancien** [openego/egon-webapp#11]
@henhuy I couldn't find where I could play with the chart style. Can you tell me which file(s) I should look at?

**Comment by henhuy** [comment]
What chart style do you mean? The dummy demand chart?
You can find this in JS part of `templates/canvases/panel.html`.

**Comment by bmlancien** [comment]
Yes, exactly, thanks, I didn't see that it was in the html file...

**Comment by finnus** [comment]
Chart has been removed on the left panel.
